### PR TITLE
Migrate KubernetesSecretConfigStore to @configu/integrations

### PR DESCRIPTION
**Pull request by akshay11298**
Closes https://github.com/configu/configu/issues/517

### CODE REVIEW

**Review by davidmeirlevy — APPROVED** [review]
LGTM

**Comment by davidmeirlevy** [comment]
@akshay11298 thanks for you PR!

**Comment by davidmeirlevy** [comment]
@akshay11298 can you please resolve the conflicts?

**Comment by akshay11298** [comment]
@davidmeirlevy resolved the conflicts :)

**Comment by pelegpor** [comment]
Hi @akshay11298 ,

Here are the details for claiming your Hacktoberfest prizes! 🎉 Check out [#465  (comment)](https://github.com/configu/configu/issues/465#issuecomment-2498550259) for more information or simply fill out the form here: [Claim Your Swag](https://share-eu1.hsforms.com/2SVc5VKY3Thi04Bvjh17WKw2e62o0).  

Remember, you only need to fill out the form once for all your PRs. 😊

**Pull request merged**
