### PR TITLE
Allow provision of a default store

### LINKED ISSUE #449: Default Store `.configu`
### Suggestion

- add `default` marker to a store which will be used by default when Store flag is omitted in upper level Interfaces
- Consider change `init` command
- Consider adding a cfgu editor commands

### Motivation

_No response_

### Context

_No response_

### PR DESCRIPTION
**Pull request by jamesL92**
Closes #449 

It'd be nice if we could add some sort of validation when parsing the `.configu` file, to ensure that, among other things, we don't specify two `default` stores. However, since we don't currently have any form of runtime validation of the file, I figured it'd be a bit out of scope for this PR.

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
@jamesL92 thanks for this PR!

@rannn505 can you please review this PR? Thanks!


@jamesL92 By the way, please mention that you take this issue on the issue itself before you start it, so we won't start fixing it ourselves at the same time.

**Comment by jamesL92** [comment]
> @jamesL92 By the way, please mention that you take this issue on the issue itself before you start it, so we won't start fixing it ourselves at the same time.
Yup no probelm, shall do going forward :+1:

**Review by rannn505 — APPROVED** [review]
@jamesL92 smooth 🚀

**Comment by rannn505** [comment]
@jamesL92 I'm going to merge this one, but we'll keep the issue open as it will need to be re-implemented in the next generation of the codebase (#455).

**Pull request merged**
