### PR TITLE
Implement `CreditCard` `Cfgu Type`

### LINKED ISSUE #142: Implement `CreditCard` `Cfgu Type`
**Description**

Add a `CreditCard` type to the Cfgu type system of Configu.

Using `type: CreditCard` in a ConfigSchema should enforce a valid Credit Card number (amex, visa, mastercard, etc..) as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "CreditCard"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://en.wikipedia.org/wiki/Credit_card

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
Closes #142

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
@SanchitMahajan236 thanks for this PR!

**Review by davidmeirlevy — APPROVED** [review]
LGTM

**Comment by davidmeirlevy** [comment]
@SanchitMahajan236 notice you have got a lint error. please fix it so we can merge 🙏 .

**Comment by RichardAkman** [comment]
Hi @SanchitMahajan236,

I noticed you decided to close this PR, and I was curious about the reason. It was approved and just needed the small adjustment that David mentioned before merging. If you’ve encountered any issues or need assistance with the final changes, feel free to let us know—we’re happy to help.

Thanks!

**Comment by SanchitMahajan236** [comment]
I ran through some problem at my end and to get it sorted I had to delete the repo and fork it again that is why I have generated a new PR #485 . Sorry, for the inconvenience caused by me.

**Pull request closed without merging**
