### PR TITLE
Add AWSSecretsManagerConfigStore to @configu/integrations

### LINKED ISSUE #510: Migrate `AWSSecretsManagerConfigStore` to `@configu/integrations`
### Suggestion

Migrate the `AWSSecretsManagerConfigStore` from its current setup to the new `@configu/integrations` module as part of the major restructuring. The goal is to move all third-party integrations, including stores, expressions, and libraries, to `@configu/integrations`.

### Motivation

This migration is part of a larger effort to better organize and modularize the product. Moving the `AWSSecretsManagerConfigStore` will align with the new structure, making the system cleaner and more maintainable.

### Context

You can refer to the already migrated stores for guidance:  
[Migrated stores in integrations](https://github.com/configu/configu/tree/main/packages/integrations/stores).

Base stores implementations from `@configu/ts` can be found here:  
[Base stores in TS](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/ts/src/stores).

The old node-based stores were previously in `@configu/node`:  
[Node stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/node/src/stores).

The old browser-based stores were previously in `@configu/browser`:  
[Browser stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/browser/src/stores).

### PR DESCRIPTION
**Pull request by Prathamesh010**
Closes #510

### CODE REVIEW

**Review by RichardAkman — CHANGES_REQUESTED** [review]
Looks great ⭐ , please update your PR against main and run `pnpm i` to resolve the conflict before we can approve and merge.

**Comment by Prathamesh010** [comment]
The lock file is updated now. Please have a look.

**Review by RichardAkman — APPROVED** [review]
LGTM, great work ⭐

**Comment by pelegpor** [comment]
Hi @Prathamesh010 ,

Here are the details for claiming your Hacktoberfest prizes! 🎉 Check out [#465  (comment)](https://github.com/configu/configu/issues/465#issuecomment-2498550259) for more information or simply fill out the form here: [Claim Your Swag](https://share-eu1.hsforms.com/2SVc5VKY3Thi04Bvjh17WKw2e62o0).  

Remember, you only need to fill out the form once for all your PRs. 😊

**Pull request merged**
