### PR TITLE
Feat/py additional key stores

### LINKED ISSUE #124: Vault based configuration
**Description**
Hashicorp vault is widely used a mechanism to store secrets and with increasing environments having the ease to manage that in vault will be really helpful.

**Motivation**
Secret and configuration with Hashicorp vault will be a really welcoming feature.

### PR DESCRIPTION
**Pull request by jamesL92**
Implementation of remaining key-value stores in Python.

Should resolve #124 among other things.

### CODE REVIEW

**Comment by jamesL92** [comment]
Rebased on top of main :slightly_smiling_face:

**Review by RonConfigu — APPROVED** [review]
Hi @jamesL92,

I wanted to express my gratitude for your contribution once again! Your work has been exceptional, and I truly appreciate it. 🚀 🥇

During the process of reviewing and testing your code, I encountered a few additional issues that need to be addressed before I can publish this branch. However, I want to assure you that none of these problems should have any impact on your code.

Rest assured, I will inform you as soon as this branch is published.

Thank you once more for your efforts!

**Comment by rannn505** [comment]
@RonConfigu How are we doing with this awesome PR?

**Comment by RonConfigu** [comment]
@jamesL92 released 💯

**Pull request merged**
