### PR TITLE
Implemented `CreditCard` `Cfgu Type`

### LINKED ISSUE #142: Implement `CreditCard` `Cfgu Type`
**Description**

Add a `CreditCard` type to the Cfgu type system of Configu.

Using `type: CreditCard` in a ConfigSchema should enforce a valid Credit Card number (amex, visa, mastercard, etc..) as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "CreditCard"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://en.wikipedia.org/wiki/Credit_card

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
Closes #142

### CODE REVIEW

**Comment by SanchitMahajan236** [comment]
Hi @davidmeirlevy , can you please review my pull request. And, please let me know in case any change is to be made.

**Comment by davidmeirlevy** [comment]
@SanchitMahajan236 thanks for this PR!

It looks like this PR doesn't pass the lint check.
please run `pnpm format --write` to fix this issue. 🙏

**Review by davidmeirlevy — CHANGES_REQUESTED** [review]
LGTM, but please fix the format issue using `pnpm format --write`

**Comment by SanchitMahajan236** [comment]
@davidmeirlevy, please approve as I have synced the fork and as you have already corrected the lint error in one of your recent PR, it shouldn't be problem now.

**Review by davidmeirlevy — APPROVED** [review]

**Comment by SanchitMahajan236** [comment]
@davidmeirlevy, I ran `pnpm run test` in order to see the error I am getting and I saw that it was connected to the PR #492 in which you coded the registry.test.ts file. This file's import statement for Registry.ts had `../registry` but it should have been `../Registry`. After I corrected it I got the error as shown in the screenshot below 

Screenshot 2024-10-07 190150

Please help to mitigate this issue.

**Comment by davidmeirlevy** [comment]
yeah, we're working simultaneously on related features, and this registry store was public data before.
leave it with this warning, the tests will pass anyway.

we'll change the test later to retrieve the data from a public source later.
or if you like - I can create an issue for that and you can do it in a seaprate PR.

**Pull request merged**
