### PR TITLE
Implement Support Schema Aliasing in .configu Configuration File

### LINKED ISSUE #360: Support Schema Aliasing in `.configu` Configuration File
### Suggestion

Introduce a `schemas` section to the `.configu` configuration file to allow aliasing of schema file paths. This feature enables users to refer to schemas by simple, memorable names rather than specifying full file paths in command-line operations. The `schemas` dictionary maps custom alias names to relative or absolute paths of `ConfigSchema` files.

**Example Configuration:**
```yaml
stores:
  Configu:
    type: configu
    configuration:
      credentials:
        org: configu
  # Other store configurations...

schemas:
  common: 'packages/common/common.cfgu.json'
  infra: 'packages/infra/infra.cfgu.json'
  dal: 'packages/dal/dal.cfgu.json'
  api: 'packages/api/api.cfgu.json'

scripts:
  dev:api: |
    configu eval --schema 'common' \
      | configu eval --schema 'infra' \
      | configu eval --schema 'dal' \
      | configu eval --schema 'api' \
      | configu export --format 'Dotenv' > packages/api/.env
  # Other script configurations...
```
In this setup, schema aliases such as `common`, `infra`, `dal`, `api` are defined under `schemas`, pointing to their respective JSON schema files. This allows the user to utilize these aliases in CLI commands for more concise and readable scripts.

### Motivation

Schema aliasing simplifies the usage of frequently referenced schemas across various scripts and commands within a project. By providing a centralized place for schema path definitions, this feature reduces redundancy, minimizes potential for errors in path specification, and enhances readability and maintainability of configuration-related scripts.

### Context

The `.configu` file supports both YAML and JSON formats, offering flexibility in how configurations are structured. This proposal extends its utility by leveraging it for schema path aliasing, encouraging a more organized and efficient approach to managing configuration schema references within Configu projects.

This enhancement builds on existing functionalities of the `.configu` configuration file, aligning with the goal of making Configu more user-friendly and adaptable to diverse project structures.

### PR DESCRIPTION
**Pull request by RonConfigu**
Closes #360

### CODE REVIEW

**Review by RichardAkman — APPROVED** [review]
LGTM, great work!! 🌟

**Comment by rannn505** [comment]
This is not working with relative paths.

image
image

you should set the cwd as the location of the .configu as done in the run command (configu run -s <script> - the cript might contain pathes which should be relative to the acutal .configu file!)

**Comment by rannn505** [comment]
This is not working with relative paths.

image
image

you should set the cwd as the location of the .configu as done in the run command (configu run -s <script> - the cript might contain pathes which should be relative to the acutal .configu file!)

**Comment by RonConfigu** [comment]
> This is not working with relative paths.
> 
> image image
> you should resolve the path with the cwd set as the location of the .configu - as done in the run command (configu run -s <script> - the cript might contain pathes which should be relative to the acutal .configu file!)

Hi @rannn505,
I assume from the picture your current pwd is `~dev/configu/examples/hello-world`.
schema:test2 is relative to where the .configu is, meaning,  `~dev/configu/examples/hello-world/examples/hello-world/start.cfgu.json`. by convention, relative paths upwards starts with `../`.. 

@pelegpor looked at the behavior and approved merging for now and follow-up with you once you're available.

Thanks, 
Ron

**Pull request merged**
