### PR TITLE
Refactor EvalCommand to Improve Modularity and Maintainability

### PR DESCRIPTION
**Pull request by HarshMN2345**
This PR refactors the EvalCommand class for better readability, maintainability, and modularity. Key changes include modularizing core logic, improving flow control with lodash utilities, introducing a validation entry point, simplifying constant evaluation using Expression.parse, and refining error handling for required configs and validation failures.

### CODE REVIEW

**Comment by HarshMN2345** [comment]
Hi @gevaperry I’ve added this PR. Please check and review.

**Comment by rannn505** [comment]
@davidmeirlevy can you please review this one?

@HarshMN2345 can you please first open an issue explaining why this change is needed, and how it is improving the things you mentioned in your comment 🙏🏽

**Comment by davidmeirlevy** [comment]
@HarshMN2345 can you also add a test file to make sure it has the same behavior?

**Comment by HarshMN2345** [comment]
hi @rannn505 i have opened the issue #578 for the same

**Comment by RichardAkman** [comment]
Closed following https://github.com/configu/configu/issues/578#issuecomment-2453412744

**Pull request closed without merging**
