### PR TITLE
Implement `CreditCard` `Cfgu Type`

### LINKED ISSUE #142: Implement `CreditCard` `Cfgu Type`
**Description**

Add a `CreditCard` type to the Cfgu type system of Configu.

Using `type: CreditCard` in a ConfigSchema should enforce a valid Credit Card number (amex, visa, mastercard, etc..) as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "CreditCard"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://en.wikipedia.org/wiki/Credit_card

### PR DESCRIPTION
**Pull request by Sadaf-A**
This PR Implements `CreditCard` `Cfgu Type`
Resolves #142

### CODE REVIEW

**Review by RonConfigu — CHANGES_REQUESTED** [review]
Great job! 🥇 
Thanks for your contribution @Sadaf-A 💯 

Please merge `main` to this branch and rename the PR in accordance with our contribution guidelines:
Implement `CreditCard` `CfguType`

**Review by RonConfigu — APPROVED** [review]
🚀

**Comment by jamesL92** [comment]
Note the potential compliance issue mentioned in https://github.com/configu/configu/issues/142#issuecomment-1619228747. Is Configu prepared for any potential compliance concerns of explicitly storing `CreditCard` information? Still a great change to have, however if potential compliance issues need addressing it may be worth raising an exception to this particular change when trying to explicitly upsert a `CreditCard` to a `ConfiguConfigStore`.

@rannn505 @RonConfigu could you advise on this?

**Comment by RonConfigu** [comment]
@Sadaf-A Please tag future PRs with correct label. `feat` in this case.
The correct label will present on the issue for ref.

Thanks

**Review by RonConfigu — COMMENTED** [review]
Hello @Sadaf-A,

In light of the community's expressed concerns surrounding the security and compliance aspects associated with the storage of credit card information, we have reached the decision to close this PR temporarily. Our aim is to thoroughly reconsider both the issue at hand and the most appropriate approach to address it effectively.

We want to extend our sincere gratitude for your significant contribution. Your understanding of this decision is greatly appreciated.

Best regards,
Ron

**Comment by Sadaf-A** [comment]
> Hello @Sadaf-A,
> 
> In light of the community's expressed concerns surrounding the security and compliance aspects associated with the storage of credit card information, we have reached the decision to close this PR temporarily. Our aim is to thoroughly reconsider both the issue at hand and the most appropriate approach to address it effectively.
> 
> We want to extend our sincere gratitude for your significant contribution. Your understanding of this decision is greatly appreciated.
> 
> Best regards,
> Ron

That is great! No point in rushing things.

**Pull request closed without merging**
