### PR TITLE
fix: redirecting Recipes in docs

### LINKED ISSUE #273: Recipes is not redirecting to the repipe docs in README.md
**Actual behavior**
while reading to the README.md at the Recipes section it docent redirect to the  Recipes  docs .

**To Reproduce**
apply redirect on the Recipes at README.md
 
**Expected behavior**
It should redirect to the Recipes docs 
**Screenshot**

Screenshot 2023-10-03 at 9 55 42 PM

**Additional context**
if the issue is valid then I would like to work on this

### PR DESCRIPTION
**Pull request by OmkarDate29**
Fix #273
This PR fixe the bug that regarding redirection of Recipes to docs

### CODE REVIEW

**Review by RonConfigu — APPROVED** [review]
Hi @OmkarDate29,

Thank you for your contribution 💯 

Great work.

Ron

**Comment by 7h3-3mp7y-m4n** [comment]
Hey, that's a very bad practice. @OmkarDate29 If you wanted to work on this, you could have pinged me . Stealing issues are really bad .

**Comment by pelegpor** [comment]
Hello @7h3-3mp7y-m4n ,

I understand your frustration, and I apologize for any confusion. We're all here for the same cause, and collaboration is at the heart of open-source. I truly value your contributions and dedication to the project.

Please feel free to take a look at any other open issues or reach out to me directly on Discord. We can discuss and identify a new task that aligns with your interests and expertise.

Thank you for your understanding and continued support.

Best regards,
Peleg

**Comment by pelegpor** [comment]
Hello @OmkarDate29,

Thank you for your contribution 🚀

**Comment by pelegpor** [comment]
Hi, check out the https://github.com/configu/configu/issues/266#issuecomment-1826770636 for details regarding the Hacktoberfest rewards

**Comment by OmkarDate29** [comment]
Hi Peleg Porat,

I hope this message finds you well! I wanted to express my gratitude for
keeping me in the loop regarding the details of the Hacktoberfest rewards.

Your prompt and informative update is greatly appreciated. It's wonderful
to be part of such an engaged and collaborative community, and your efforts
in keeping everyone informed do not go unnoticed.

If there's anything else I need to know or contribute to, please feel free
to let me know. I'm looking forward to the upcoming Hacktoberfest rewards
and the continued success of our collaborative efforts.

Once again, thank you for your dedication and the timely update!

Best regards,
Omkar Date

**Pull request merged**
