### PR TITLE
fix the pnpm ci integration to ignore lockfile

### LINKED ISSUE #561: Fix CI integrations to ignore lockfile
### Suggestion

on the ci-integrations pipeline, make sure the `pnpm install` will ignore the lockfile problem.
it can be done in two ways:
1. (recommended): change NODE_ENV to development, or use `pnpm install` instead of `pnpm ci`, to make sure it ignores the lockfile changes.
2. (not recommended, use it if the first one not working): remove the pnpm lock file before the install step, so it will force to ignore it.

### Motivation

we want the CI to pass for contribution PRs, and will test the actual integrations build without falling on non-relevant problems on installation.

### Context

_No response_

### PR DESCRIPTION
**Pull request by RS-labhub**
#### description
image

Closes #561

### CODE REVIEW

**Comment by RS-labhub** [comment]
Seems like no file in the workflows to check this

**Comment by RS-labhub** [comment]
So what should I do now @rannn505 (referring to this message: https://github.com/configu/configu/issues/561#issuecomment-2417717857)

**Review by davidmeirlevy — APPROVED** [review]
LGTM

**Comment by RichardAkman** [comment]
Closed following https://github.com/configu/configu/issues/561#issuecomment-2444441271

**Pull request closed without merging**
