### PR TITLE
Add `CreditCard` Cfgu type

### PR DESCRIPTION
**Pull request by bharathgaddam1712**
credit card Schema

### CODE REVIEW

**Comment by Sadaf-A** [comment]
https://github.com/configu/configu/pull/204#pullrequestreview-1582441229

hey @bharathgaddam1712, Thank you for your time and consideration but as the comment above mentions `CreditCard` is something which is yet to be discussed thoroughly before being implemented.

**Comment by rannn505** [comment]
Dear @bharathgaddam1712, Thank you for your enthusiastic attempt; your effort is much appreciated! To further refine your contribution, I'd recommend taking a look at [@Sadaf-A's PR](https://github.com/configu/configu/pull/206) which serves as a stellar reference on how to add a `Cfgu type`.

We're looking forward to seeing your refined contribution. Your initiative is bringing great value to our project. Should you have any questions or need further clarification, feel free to reach out.

**Comment by RichardAkman** [comment]
Hi @bharathgaddam1712,

I hope you're doing well! I wanted to check in on the status of this PR. It has been two weeks since the last update, and I'm eager to see how we can move this forward. If there are any blockers or additional information needed from our side, please don't hesitate to let us know.

**Comment by RichardAkman** [comment]
Hi @bharathgaddam1712,

I hope you're doing well! I wanted to provide an update on this PR. After careful consideration, we've decided to close this PR to give other contributors an opportunity to work on it.

We appreciate the effort you've put into this, and your contributions are always valuable.

Thank you for your understanding, and we hope to see more of your work in the future!

**Pull request closed without merging**
