### PR TITLE
Implement `etcd ConfigStore` in `Node.js SDK`

### LINKED ISSUE #145: Implement `etcd` `ConfigStore` in Node.js SDK
**Description**

- Plan a `Config` accommodation in the etcd storage.
- Add `EtcdConfigStore` class to the Node.js SDK stores.
- A quick search indicates that [etcd3](https://www.npmjs.com/package/etcd3) library is the most "suitable" for use during implementation.
- We would be happy to hear more suggestions, or we can implement the APIs ourselves.

**Motivation**

Extending Configu's [available stores](https://configu.com/docs/config-store/#available-stores) collection.
This ConfigStore will be made available in the Configu CLI since the Node.js SDK is used internally.

**Additional context**

- https://etcd.io/
- https://etcd.io/docs/v3.3/integrations/
- https://configu.com/docs/config-store/
- https://github.com/configu/configu/blob/main/types/ConfigStore.ts
- https://github.com/configu/configu/tree/main/ts/packages/node/src/stores

image

### PR DESCRIPTION
**Pull request by Sadaf-A**
This PR implements `etcd ConfigStore` in `Node.js SDK`
Resolves #145

### CODE REVIEW

**Comment by Sadaf-A** [comment]
@RonConfigu I hope that this is satisfactory. I'm sorry for overlooking linting previously.

**Comment by RonConfigu** [comment]
Thanks 💯 
I'll take a look asap

**Review by RonConfigu — CHANGES_REQUESTED** [review]
Hi @Sadaf-A 

Thank you for contribution once again! 👍 💯 
The store looks good to me 🥇

Please change the following:
1. The file name shouldn't be `etcd3.ts` but `etcd.ts`. etcd is not the library you chose to communicate with it.
2. Please add `export * from './stores/etcd';` to `ts/packages/node/src/index.ts` (Notice it is A-B ordered). I can see you took inspiration from `keyv store` and it's great! Nevertheless. You should always keep your eyes open for bugs/mistakes. Without exporting the store back to the package it's not usable. (I will fix keyv)
3. Make sure your up-to-date with `main`

Great job overall! Thanks

Ron

**Comment by Sadaf-A** [comment]
> Hi @Sadaf-A
> 
> Thank you for contribution once again! 👍 💯 The store looks good to me 🥇
> 
> Please change the following:
> 
>     1. The file name shouldn't be `etcd3.ts` but `etcd.ts`. etcd is not the library you chose to communicate with it.
> 
>     2. Please add `export * from './stores/etcd';` to `ts/packages/node/src/index.ts` (Notice it is A-B ordered). I can see you took inspiration from `keyv store` and it's great! Nevertheless. You should always keep your eyes open for bugs/mistakes. Without exporting the store back to the package it's not usable. (I will fix keyv)
> 
>     3. Make sure your up-to-date with `main`
> 
> 
> Great job overall! Thanks
> 
> Ron

Thanks for your review! I will try to make the requested changes as soon as I can.

**Comment by rannn505** [comment]
@Sadaf-A,

I've successfully completed end-to-end testing for the `EtcdConfigStore`. Great news—it's working seamlessly!

To run the etcd server, I used Docker with the following command:
```bash
docker run --rm --name Etcd --env 'ETCD_ROOT_PASSWORD=root' --publish 2379:2379 --publish 2380:2380 bitnami/etcd
```

For the actual test, I utilized the `playground.ts` file and executed the following TypeScript code:
```typescript
import { EtcdConfigStore, ConfigSet, InMemoryConfigSchema, UpsertCommand, EvalCommand, ExportCommand } from '.';

(async () => {
  const store = new EtcdConfigStore({
    hosts: ['127.0.0.1:2379'],
    auth: { username: 'root', password: 'root' },
  });

  const set = new ConfigSet('test');

  const schema = new InMemoryConfigSchema(
    {
      K11: {
        type: 'Number',
      },
      K12: {
        type: 'String',
      },
    },
    's1',
  );

  await new UpsertCommand({
    store,
    set,
    schema,
    configs: {
      K11: '10',
      K12: 'ran',
    },
  }).run();
  const data = await new EvalCommand({ store, set, schema }).run();
  const resp = await new ExportCommand({ data }).run();
  console.log(resp);
})();

```

To run the code, I used:
```bash
npx tsx ts/packages/node/src/playground.ts
```

Everything executed as expected, confirming that your implementation is solid. I'm now moving ahead with merging the code. Kudos for your exceptional work on this store—it's evident that you've put a lot of effort into it, and you absolutely deserve credit for such high-quality work. 🚀

**Comment by Sadaf-A** [comment]
> @Sadaf-A,
> 
> I've successfully completed end-to-end testing for the `EtcdConfigStore`. Great news—it's working seamlessly!
> 
> To run the etcd server, I used Docker with the following command:
> ```bash
> docker run --rm --name Etcd --env 'ETCD_ROOT_PASSWORD=root' --publish 2379:2379 --publish 2380:2380 bitnami/etcd
> ```
> 
> For the actual test, I utilized the `playground.ts` file and executed the following TypeScript code:
> ```typescript
> import { EtcdConfigStore, ConfigSet, InMemoryConfigSchema, UpsertCommand, EvalCommand, ExportCommand } from '.';
> 
> (async () => {
>   const store = new EtcdConfigStore({
>     hosts: ['127.0.0.1:2379'],
>     auth: { username: 'root', password: 'root' },
>   });
> 
>   const set = new ConfigSet('test');
> 
>   const schema = new InMemoryConfigSchema(
>     {
>       K11: {
>         type: 'Number',
>       },
>       K12: {
>         type: 'String',
>       },
>     },
>     's1',
>   );
> 
>   await new UpsertCommand({
>     store,
>     set,
>     schema,
>     configs: {
>       K11: '10',
>       K12: 'ran',
>     },
>   }).run();
>   const data = await new EvalCommand({ store, set, schema }).run();
>   const resp = await new ExportCommand({ data }).run();
>   console.log(resp);
> })();
> 
> ```
> 
> To run the code, I used:
> ```bash
> npx tsx ts/packages/node/src/playground.ts
> ```
> 
> Everything executed as expected, confirming that your implementation is solid. I'm now moving ahead with merging the code. Kudos for your exceptional work on this store—it's evident that you've put a lot of effort into it, and you absolutely deserve credit for such high-quality work. 🚀 

Thanks for testing and reviewing, that is great to hear. 
I look forward to implementing more config stores !

**Pull request merged**
